DROP TYPE IF EXISTS chat_event_enum;
CREATE TYPE chat_event_enum AS ENUM ('timeout', 'ban', 'unban', 'untimeout');


DROP TYPE IF EXISTS app_role_enum;
CREATE TYPE app_role_enum AS ENUM ('user', 'staff');


CREATE TABLE IF NOT EXISTS tc_user(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64) NOT NULL,
    password VARCHAR(256) NOT NULL,
    created_at DATE DEFAULT CURRENT_DATE,
    updated_at DATE DEFAULT NULL,
    is_banned BOOLEAN DEFAULT FALSE,
    is_partner BOOLEAN DEFAULT FALSE,
    first_livestream DATE DEFAULT NULL,
    last_livestream DATE DEFAULT NULL,
    stream_token TEXT DEFAULT NULL,
    avatar TEXT DEFAULT NULL,
    offline_background TEXT NOT NULL DEFAULT 'default_offline_background.png',
    description TEXT DEFAULT NULL,
    links TEXT[] DEFAULT NULL,
    tags TEXT[] DEFAULT NULL,
    app_role app_role_enum NOT NULL DEFAULT 'user',

    PRIMARY KEY (id),
    UNIQUE (name)
);


CREATE TABLE IF NOT EXISTS tc_user_chat_event(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_channel INTEGER NOT NULL,
    id_moderator INTEGER NOT NULL,
    id_user INTEGER NOT NULL,
    created_at DATE NOT NULL DEFAULT CURRENT_DATE,
    chat_event chat_event_enum NOT NULL,
    timeout_for INTEGER DEFAULT NULL,

    FOREIGN KEY (id_channel) REFERENCES tc_user (id),
    FOREIGN KEY (id_moderator) REFERENCES tc_user (id),
    FOREIGN KEY (id_user) REFERENCES tc_user (id)
);


CREATE TABLE IF NOT EXISTS tc_category(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64) NOT NULL,
    link VARCHAR(64) NOT NULL,
    created_at DATE DEFAULT CURRENT_DATE,
    is_safe BOOLEAN DEFAULT TRUE,
    viewers INTEGER NOT NULL DEFAULT 0,
    image TEXT DEFAULT NULL,

    PRIMARY KEY (id),
    UNIQUE (link)
);


CREATE TABLE IF NOT EXISTS tc_tag(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(32) NOT NULL,

    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS tc_livestream(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_user INTEGER NOT NULL,
    id_category INTEGER NOT NULL,
    is_live BOOLEAN NOT NULL DEFAULT FALSE,
    viewers INTEGER NOT NULL DEFAULT 0,
    title TEXT DEFAULT NULL,
    started_at INTEGER DEFAULT NULL,
    ended_at INTEGER DEFAULT NULL,
    is_multistream BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY (id),
    FOREIGN KEY (id_category) REFERENCES tc_category(id),
    FOREIGN KEY (id_user) REFERENCES tc_user (id)
);


CREATE TABLE IF NOT EXISTS tc_subscription_tier(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(32) NOT NULL,
    cost DECIMAL(2) NOT NULL,

    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS tc_user_subscriber(
    id_user INTEGER NOT NULL,
    id_subscriber INTEGER NOT NULL,
    first_subscription DATE DEFAULT NULL,
    last_subscription DATE DEFAULT NULL,
    subscription_count INTEGER DEFAULT NULL,
    id_subscription_tier INTEGER DEFAULT NULL,

    UNIQUE (id_user, id_subscriber),
    FOREIGN KEY (id_user) REFERENCES tc_user (id),
    FOREIGN KEY (id_subscriber) REFERENCES tc_user (id),
    FOREIGN KEY (id_subscription_tier) REFERENCES tc_subscription_tier (id)
);


CREATE TABLE IF NOT EXISTS tc_user_follow(
    id_user INTEGER NOT NULL,
    id_follow INTEGER NOT NULL,
    following_from DATE DEFAULT CURRENT_DATE,

    UNIQUE (id_user, id_follow),
    FOREIGN KEY (id_user) REFERENCES tc_user (id),
    FOREIGN KEY (id_follow) REFERENCES tc_user (id)
);


CREATE TABLE IF NOT EXISTS tc_category_tag(
    id_category INTEGER NOT NULL,
    id_tag INTEGER NOT NULL,

    UNIQUE (id_category, id_tag),
    FOREIGN KEY (id_category) REFERENCES tc_category (id),
    FOREIGN KEY (id_tag) REFERENCES tc_tag (id)
);
