// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "no",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/categories": {
            "get": {
                "description": "Retrieves a list of categories with optional pagination and sorting parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "List categories with pagination and sorting",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of items per page",
                        "name": "count",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Sort order (asc or desc)",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of categories",
                        "schema": {
                            "$ref": "#/definitions/category.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameter",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    },
                    "500": {
                        "description": "Internal server error while fetching categories",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new category with the given details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Add a new category",
                "parameters": [
                    {
                        "description": "Category creation request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/category.PostRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content - category created successfully"
                    },
                    "400": {
                        "description": "Bad Request: invalid data",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: failed to add category",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    }
                }
            }
        },
        "/categories/{categoryIdentifier}": {
            "get": {
                "description": "Retrieves detailed information about a category by either its numeric ID or a unique link (slug).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Get category by ID or link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category identifier (either numeric ID or unique link)",
                        "name": "categoryIdentifier",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Category found successfully",
                        "schema": {
                            "$ref": "#/definitions/category.GetResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a category entity identified by either its numeric ID or unique link (slug).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Delete category by ID or link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category identifier (either numeric ID or unique link)",
                        "name": "categoryIdentifier",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content - category delted successfully"
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates a category entity using provided fields, identified by either numeric ID or unique link (slug).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Update category by ID or link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category identifier (either numeric ID or unique link)",
                        "name": "categoryIdentifier",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update in the category",
                        "name": "patchRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/category.PatchRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content - category updated successfully"
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    }
                }
            }
        },
        "/follow/{username}": {
            "get": {
                "description": "Returns json response",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follow"
                ],
                "summary": "is user a follower of other user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "follower",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "followed",
                        "name": "followed",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/follow.GetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    }
                }
            },
            "post": {
                "description": "Allows the authenticated user to follow another user by username",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follow"
                ],
                "summary": "Follow a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username of the user to follow",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username of the user to be followed",
                        "name": "following",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Follow successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request: user mismatch",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: failed to follow user",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Allows the authenticated user to unfollow another user by username",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follow"
                ],
                "summary": "Unfollow a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username of the user to unfollow",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username of the user to be unfollowed",
                        "name": "unfollowing",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Unfollow successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request: user mismatch",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: failed to unfollow user",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    }
                }
            }
        },
        "/follows": {
            "get": {
                "description": "Lists the followees of a given follower username. If ` + "`" + `extended=true` + "`" + ` is passed as a query parameter, returns detailed info per followee.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follow"
                ],
                "summary": "Retrieve follower's follow list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Follower username whose follow list is requested",
                        "name": "follower",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "If set to 'true', returns extended follow list details",
                        "name": "extended",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Extended follow list response",
                        "schema": {
                            "$ref": "#/definitions/follow.ListExtendedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request: follower username is missing",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    },
                    "500": {
                        "description": "Internal server error while retrieving follow list",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    }
                }
            }
        },
        "/livestream/{username}": {
            "patch": {
                "description": "Update livestream information like title and category for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "livestream"
                ],
                "summary": "Update livestream data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Patch livestream request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/livestream.PatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful update response",
                        "schema": {
                            "$ref": "#/definitions/livestream.PatchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request or unauthorized update attempt",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    },
                    "500": {
                        "description": "Internal server error updating livestream",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    }
                }
            }
        },
        "/livestreams": {
            "get": {
                "description": "Retrieves a paginated list of livestreams filtered by category or category ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "livestream"
                ],
                "summary": "List livestreams by category or category ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category name to filter by",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Category ID to filter by",
                        "name": "categoryId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number for pagination (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of results per page (default 10)",
                        "name": "count",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Livestream list response",
                        "schema": {
                            "$ref": "#/definitions/livestream.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request: missing or invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    }
                }
            }
        },
        "/livestreams/{username}": {
            "get": {
                "description": "Retrieves livestream information for the specified streamer username",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "livestream"
                ],
                "summary": "Get livestream data by username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Streamer Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/livestream.GetResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Starts a livestream if the authenticated user matches the username in the path",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "livestream"
                ],
                "summary": "Start a new livestream for a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Livestream start data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/livestream.PostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/livestream.PostResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Stops the livestream if the authenticated user matches the username in the path",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "livestream"
                ],
                "summary": "Stop a livestream for a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/livestream.DeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/er.RequestError"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authenticate user and return access token (refresh token set as cookie)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Access token returned",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid credentials or request data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Register new user account and return access token (refresh token set as cookie)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User registration",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Access token returned",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "User already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List users with optional filters (staff only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List all users",
                "parameters": [
                    {
                        "description": "List filters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid claims or insufficient permissions",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new user account with name, password, and optional avatar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create new user",
                "parameters": [
                    {
                        "description": "User creation data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.PostRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid request data or missing fields",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Username already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{username}": {
            "get": {
                "description": "Retrieve user information by username",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.GetResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/user.GetResponseNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete authenticated user's account by providing user ID in request body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User ID to delete",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid claims, identity mismatch, or invalid request data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update authenticated user's profile information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.PatchRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid claims, identity mismatch, or invalid request data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Username already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "access": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterResponse": {
            "type": "object",
            "properties": {
                "access": {
                    "type": "string"
                }
            }
        },
        "category.Category": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isSafe": {
                    "type": "boolean"
                },
                "link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "thumbnail": {
                    "type": "string"
                },
                "viewers": {
                    "type": "integer"
                }
            }
        },
        "category.GetResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/category.Category"
                }
            }
        },
        "category.ListResponse": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/category.ListResponseItem"
                    }
                }
            }
        },
        "category.ListResponseItem": {
            "type": "object",
            "properties": {
                "is_safe": {
                    "type": "boolean"
                },
                "link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "thumbnail": {
                    "type": "string"
                },
                "viewers": {
                    "type": "integer"
                }
            }
        },
        "category.PatchRequest": {
            "type": "object",
            "properties": {
                "is_safe": {
                    "type": "boolean"
                },
                "link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "thumbnail": {
                    "type": "string"
                }
            }
        },
        "category.PostRequest": {
            "type": "object",
            "properties": {
                "is_safe": {
                    "type": "boolean"
                },
                "link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "thumbnail": {
                    "type": "string"
                }
            }
        },
        "er.RequestError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "follow.GetResponse": {
            "type": "object",
            "properties": {
                "is_follower": {
                    "type": "boolean"
                }
            }
        },
        "follow.ListExtendedResponse": {
            "type": "object",
            "properties": {
                "follow_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/follow.ListExtendedResponseItem"
                    }
                }
            }
        },
        "follow.ListExtendedResponseItem": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "is_live": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "viewers": {
                    "type": "integer"
                }
            }
        },
        "follow.ListResponse": {
            "type": "object",
            "properties": {
                "follow_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/follow.ListResponseItem"
                    }
                }
            }
        },
        "follow.ListResponseItem": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "livestream.DeleteResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                }
            }
        },
        "livestream.GetResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "category": {
                    "$ref": "#/definitions/livestream.LivestreamCategory"
                },
                "id": {
                    "type": "integer"
                },
                "is_following": {
                    "type": "boolean"
                },
                "is_live": {
                    "type": "boolean"
                },
                "is_multistream": {
                    "type": "boolean"
                },
                "is_subscriber": {
                    "type": "boolean"
                },
                "started_at": {
                    "type": "integer"
                },
                "thumbnail": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "viewers": {
                    "type": "integer"
                }
            }
        },
        "livestream.ListResponse": {
            "type": "object",
            "properties": {
                "livestreams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/livestream.ListResponseItem"
                    }
                }
            }
        },
        "livestream.ListResponseItem": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "category": {
                    "$ref": "#/definitions/livestream.LivestreamCategory"
                },
                "is_live": {
                    "type": "boolean"
                },
                "is_multistream": {
                    "type": "boolean"
                },
                "started_at": {
                    "type": "integer"
                },
                "thumbnail": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "viewers": {
                    "type": "integer"
                }
            }
        },
        "livestream.LivestreamCategory": {
            "type": "object",
            "properties": {
                "link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "livestream.PatchRequest": {
            "type": "object",
            "properties": {
                "category_link": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "livestream.PatchResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                }
            }
        },
        "livestream.PostRequest": {
            "type": "object",
            "properties": {
                "category_link": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "livestream.PostResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "started_at": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "viewers": {
                    "type": "integer"
                }
            }
        },
        "user.DeleteRequest": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "user.GetResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "first_livestream": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_banned": {
                    "type": "boolean"
                },
                "is_partner": {
                    "type": "boolean"
                },
                "last_livestream": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "user.GetResponseNotFound": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "string"
                }
            }
        },
        "user.ListRequest": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "first_livestream": {
                    "type": "string"
                },
                "last_livestream": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "registration": {
                    "type": "string"
                },
                "sort": {
                    "type": "string"
                }
            }
        },
        "user.ListResponse": {
            "type": "object",
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.ListResponseItem"
                    }
                }
            }
        },
        "user.ListResponseItem": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "firstLivestream": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isBanned": {
                    "type": "boolean"
                },
                "isPartner": {
                    "type": "boolean"
                },
                "lastLivestream": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "user.PatchRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "is_banned": {
                    "type": "boolean"
                },
                "is_partner": {
                    "type": "boolean"
                },
                "last_livestream": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "user.PostRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8090",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "twitchclone api",
	Description:      "yes",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
