// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppRoleEnum string

const (
	AppRoleEnumUser  AppRoleEnum = "user"
	AppRoleEnumStaff AppRoleEnum = "staff"
)

func (e *AppRoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppRoleEnum(s)
	case string:
		*e = AppRoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AppRoleEnum: %T", src)
	}
	return nil
}

type NullAppRoleEnum struct {
	AppRoleEnum AppRoleEnum
	Valid       bool // Valid is true if AppRoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AppRoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppRoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppRoleEnum), nil
}

type ChatEventEnum string

const (
	ChatEventEnumTimeout   ChatEventEnum = "timeout"
	ChatEventEnumBan       ChatEventEnum = "ban"
	ChatEventEnumUnban     ChatEventEnum = "unban"
	ChatEventEnumUntimeout ChatEventEnum = "untimeout"
)

func (e *ChatEventEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatEventEnum(s)
	case string:
		*e = ChatEventEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatEventEnum: %T", src)
	}
	return nil
}

type NullChatEventEnum struct {
	ChatEventEnum ChatEventEnum
	Valid         bool // Valid is true if ChatEventEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatEventEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ChatEventEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatEventEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatEventEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatEventEnum), nil
}

type TcCategory struct {
	ID        int32
	Name      string
	Link      string
	CreatedAt pgtype.Date
	IsSafe    bool
	Viewers   int32
	Image     string
}

type TcCategoryTag struct {
	IDCategory int32
	IDTag      int32
}

type TcLivestream struct {
	ID            int32
	IDUser        int32
	IDCategory    int32
	Viewers       int32
	Title         string
	StartedAt     pgtype.Timestamptz
	IsMultistream bool
}

type TcLivestreamHistory struct {
	ID         int32
	IDUser     int32
	IDCategory int32
	Title      pgtype.Text
	StartedAt  pgtype.Timestamptz
	EndedAt    pgtype.Timestamptz
}

type TcSubscriptionTier struct {
	ID   int32
	Name string
	Cost pgtype.Numeric
}

type TcTag struct {
	ID   int32
	Name string
}

type TcUser struct {
	ID                int32
	Name              string
	Password          string
	CreatedAt         pgtype.Date
	UpdatedAt         pgtype.Date
	IsBanned          pgtype.Bool
	IsPartner         pgtype.Bool
	FirstLivestream   pgtype.Date
	LastLivestream    pgtype.Date
	StreamToken       pgtype.Text
	IsLive            bool
	Avatar            pgtype.Text
	OfflineBackground string
	Description       pgtype.Text
	Links             []string
	Tags              []string
	AppRole           AppRoleEnum
}

type TcUserChatEvent struct {
	ID          pgtype.Int4
	IDChannel   int32
	IDModerator int32
	IDUser      int32
	CreatedAt   pgtype.Timestamptz
	ChatEvent   ChatEventEnum
	TimeoutFor  pgtype.Int4
}

type TcUserFollow struct {
	IDUser        int32
	IDFollow      int32
	FollowingFrom pgtype.Date
}

type TcUserSubscriber struct {
	IDUser             int32
	IDSubscriber       int32
	FirstSubscription  pgtype.Date
	LastSubscription   pgtype.Date
	SubscriptionCount  pgtype.Int4
	IDSubscriptionTier pgtype.Int4
}
