// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userDeleteById = `-- name: UserDeleteById :exec
DELETE FROM
    tc_user
WHERE
    id = $1
`

func (q *Queries) UserDeleteById(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, userDeleteById, id)
	return err
}

const userInsert = `-- name: UserInsert :one
INSERT INTO tc_user (
    name,
    password,
    avatar)
VALUES (
    $1,
    $2,
    $3)
RETURNING
    id
`

type UserInsertParams struct {
	Name     string
	Password string
	Avatar   pgtype.Text
}

func (q *Queries) UserInsert(ctx context.Context, arg UserInsertParams) (int32, error) {
	row := q.db.QueryRow(ctx, userInsert, arg.Name, arg.Password, arg.Avatar)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const userSelectById = `-- name: UserSelectById :one
SELECT
    id,
    name,
    avatar,
    is_banned,
    is_partner,
    first_livestream,
    last_livestream
FROM
    tc_user
WHERE
    id = $1
`

type UserSelectByIdRow struct {
	ID              int32
	Name            string
	Avatar          pgtype.Text
	IsBanned        pgtype.Bool
	IsPartner       pgtype.Bool
	FirstLivestream pgtype.Date
	LastLivestream  pgtype.Date
}

func (q *Queries) UserSelectById(ctx context.Context, id int32) (UserSelectByIdRow, error) {
	row := q.db.QueryRow(ctx, userSelectById, id)
	var i UserSelectByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.IsBanned,
		&i.IsPartner,
		&i.FirstLivestream,
		&i.LastLivestream,
	)
	return i, err
}

const userUpdateById = `-- name: UserUpdateById :exec
UPDATE
    tc_user
SET
    name       = $1,
    password   = $2,
    is_banned  = $3,
    is_partner = $4,
    avatar     = $5,
    updated_at = CURRENT_DATE
WHERE
    id = $6
`

type UserUpdateByIdParams struct {
	Name      string
	Password  string
	IsBanned  pgtype.Bool
	IsPartner pgtype.Bool
	Avatar    pgtype.Text
	ID        int32
}

func (q *Queries) UserUpdateById(ctx context.Context, arg UserUpdateByIdParams) error {
	_, err := q.db.Exec(ctx, userUpdateById,
		arg.Name,
		arg.Password,
		arg.IsBanned,
		arg.IsPartner,
		arg.Avatar,
		arg.ID,
	)
	return err
}
