// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.category.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoryInsert = `-- name: CategoryInsert :one
INSERT INTO
    tc_category(name, link, viewers, image)
VALUES
    ($1, $2, $3, $4)
RETURNING id, name, link, created_at, is_safe, viewers, image
`

type CategoryInsertParams struct {
	Name    string
	Link    string
	Viewers int32
	Image   pgtype.Text
}

func (q *Queries) CategoryInsert(ctx context.Context, arg CategoryInsertParams) (TcCategory, error) {
	row := q.db.QueryRow(ctx, categoryInsert,
		arg.Name,
		arg.Link,
		arg.Viewers,
		arg.Image,
	)
	var i TcCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Link,
		&i.CreatedAt,
		&i.IsSafe,
		&i.Viewers,
		&i.Image,
	)
	return i, err
}

const categorySelect = `-- name: CategorySelect :one
SELECT
    id, name, link, created_at, is_safe, viewers, image
FROM
    tc_category
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) CategorySelect(ctx context.Context, id int32) (TcCategory, error) {
	row := q.db.QueryRow(ctx, categorySelect, id)
	var i TcCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Link,
		&i.CreatedAt,
		&i.IsSafe,
		&i.Viewers,
		&i.Image,
	)
	return i, err
}

const categorySelectMany = `-- name: CategorySelectMany :many
SELECT
    c.id AS category_id,
    c.name AS category_name,
    is_safe,
    viewers,
    image,
    t.id AS tag_id,
    t.name AS tag_name
FROM
    tc_category c
LEFT OUTER JOIN
    tc_category_tag ct ON ct.id_category = c.id
LEFT OUTER JOIN
    tc_tag t ON t.id = ct.id_tag
LIMIT $1
OFFSET $2
`

type CategorySelectManyParams struct {
	Limit  int64
	Offset int64
}

type CategorySelectManyRow struct {
	CategoryID   int32
	CategoryName string
	IsSafe       pgtype.Bool
	Viewers      int32
	Image        pgtype.Text
	TagID        pgtype.Int4
	TagName      pgtype.Text
}

func (q *Queries) CategorySelectMany(ctx context.Context, arg CategorySelectManyParams) ([]CategorySelectManyRow, error) {
	rows, err := q.db.Query(ctx, categorySelectMany, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategorySelectManyRow
	for rows.Next() {
		var i CategorySelectManyRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.IsSafe,
			&i.Viewers,
			&i.Image,
			&i.TagID,
			&i.TagName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
