// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.livestream.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const livestreamDelete = `-- name: LivestreamDelete :exec
DELETE FROM
    tc_livestream l
WHERE
    l.id_user = (
        SELECT
            id
        FROM
            tc_user
        WHERE
            name = $1
    )
`

func (q *Queries) LivestreamDelete(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, livestreamDelete, name)
	return err
}

const livestreamInsert = `-- name: LivestreamInsert :one
WITH inserted AS (
    INSERT INTO tc_livestream (
        id_user,
        id_category,
        is_multistream,
        title
    ) VALUES (
        (SELECT id FROM tc_user u WHERE u.name = $1),
        (SELECT id FROM tc_category c WHERE c.link = $2),
        FALSE,
        $3
    )
    RETURNING id, id_user, id_category, started_at, viewers, is_live, is_multistream, title
)
SELECT
    inserted.id AS livestream_id,
    u.avatar AS user_avatar,
    u.name AS user_name,
    c.link AS category_link,
    c.name AS category_name,
    started_at
FROM
    inserted
JOIN
    tc_user u ON inserted.id_user = u.id
JOIN
    tc_category c ON inserted.id_category = c.id
`

type LivestreamInsertParams struct {
	Name  string
	Link  string
	Title pgtype.Text
}

type LivestreamInsertRow struct {
	LivestreamID int32
	UserAvatar   pgtype.Text
	UserName     string
	CategoryLink string
	CategoryName string
	StartedAt    pgtype.Int4
}

func (q *Queries) LivestreamInsert(ctx context.Context, arg LivestreamInsertParams) (LivestreamInsertRow, error) {
	row := q.db.QueryRow(ctx, livestreamInsert, arg.Name, arg.Link, arg.Title)
	var i LivestreamInsertRow
	err := row.Scan(
		&i.LivestreamID,
		&i.UserAvatar,
		&i.UserName,
		&i.CategoryLink,
		&i.CategoryName,
		&i.StartedAt,
	)
	return i, err
}

const livestreamSelectById = `-- name: LivestreamSelectById :one
SELECT c.name AS cat_name,
    c.is_safe AS cat_is_safe,
    c.link AS cat_link,
    c.viewers AS cat_viewers,
    c.image AS cat_image,
    l.title AS ls_title,
    u.id AS u_id,
    u.name AS u_name,
    u.is_partner AS u_is_partner,
    u.avatar AS u_avatar,
    u.last_livestream AS u_last_livestream,
    u.description AS u_description,
    u.links AS u_links
FROM
    tc_livestream l
INNER JOIN
    tc_user u ON u.id = l.id_user
INNER JOIN
    tc_category c ON c.id = l.id_category
WHERE
    c.name = $1
`

type LivestreamSelectByIdRow struct {
	CatName         string
	CatIsSafe       pgtype.Bool
	CatLink         string
	CatViewers      int32
	CatImage        pgtype.Text
	LsTitle         pgtype.Text
	UID             int32
	UName           string
	UIsPartner      pgtype.Bool
	UAvatar         pgtype.Text
	ULastLivestream pgtype.Date
	UDescription    pgtype.Text
	ULinks          []string
}

func (q *Queries) LivestreamSelectById(ctx context.Context, name string) (LivestreamSelectByIdRow, error) {
	row := q.db.QueryRow(ctx, livestreamSelectById, name)
	var i LivestreamSelectByIdRow
	err := row.Scan(
		&i.CatName,
		&i.CatIsSafe,
		&i.CatLink,
		&i.CatViewers,
		&i.CatImage,
		&i.LsTitle,
		&i.UID,
		&i.UName,
		&i.UIsPartner,
		&i.UAvatar,
		&i.ULastLivestream,
		&i.UDescription,
		&i.ULinks,
	)
	return i, err
}

const livestreamSelectCategoryLinkById = `-- name: LivestreamSelectCategoryLinkById :one
SELECT
    link
FROM
    tc_category
WHERE
    id = $1
`

func (q *Queries) LivestreamSelectCategoryLinkById(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, livestreamSelectCategoryLinkById, id)
	var link string
	err := row.Scan(&link)
	return link, err
}

const livestreamSelectMany = `-- name: LivestreamSelectMany :many
SELECT
    c.id AS cat_id,
    c.name AS cat_name,
    c.is_safe AS cat_is_safe,
    c.viewers AS cat_viewers,
    c.image AS cat_image,
    u.id AS u_id,
    u.name AS u_name,
    u.is_partner AS u_is_partner,
    u.avatar AS u_avatar
FROM
    tc_livestream l
INNER JOIN
    tc_user u ON u.id = l.id_user
INNER JOIN
    tc_category c ON c.id = l.id_category
LIMIT $1
OFFSET $2
`

type LivestreamSelectManyParams struct {
	Limit  int64
	Offset int64
}

type LivestreamSelectManyRow struct {
	CatID      int32
	CatName    string
	CatIsSafe  pgtype.Bool
	CatViewers int32
	CatImage   pgtype.Text
	UID        int32
	UName      string
	UIsPartner pgtype.Bool
	UAvatar    pgtype.Text
}

func (q *Queries) LivestreamSelectMany(ctx context.Context, arg LivestreamSelectManyParams) ([]LivestreamSelectManyRow, error) {
	rows, err := q.db.Query(ctx, livestreamSelectMany, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LivestreamSelectManyRow
	for rows.Next() {
		var i LivestreamSelectManyRow
		if err := rows.Scan(
			&i.CatID,
			&i.CatName,
			&i.CatIsSafe,
			&i.CatViewers,
			&i.CatImage,
			&i.UID,
			&i.UName,
			&i.UIsPartner,
			&i.UAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const livestreamSelectManyFromCategory = `-- name: LivestreamSelectManyFromCategory :many
SELECT
    c.id AS cat_id,
    c.name AS cat_name,
    c.is_safe AS cat_is_safe,
    c.viewers AS cat_viewers,
    c.image AS cat_image,
    u.id AS u_id,
    u.name AS u_name,
    u.is_partner AS u_is_partner,
    u.avatar AS u_avatar
FROM
    tc_livestream l
INNER JOIN
    tc_user u ON u.id = l.id_user
INNER JOIN
    tc_category c ON c.id = l.id_category
WHERE
    c.name = $1
LIMIT $2
OFFSET $3
`

type LivestreamSelectManyFromCategoryParams struct {
	Name   string
	Limit  int64
	Offset int64
}

type LivestreamSelectManyFromCategoryRow struct {
	CatID      int32
	CatName    string
	CatIsSafe  pgtype.Bool
	CatViewers int32
	CatImage   pgtype.Text
	UID        int32
	UName      string
	UIsPartner pgtype.Bool
	UAvatar    pgtype.Text
}

func (q *Queries) LivestreamSelectManyFromCategory(ctx context.Context, arg LivestreamSelectManyFromCategoryParams) ([]LivestreamSelectManyFromCategoryRow, error) {
	rows, err := q.db.Query(ctx, livestreamSelectManyFromCategory, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LivestreamSelectManyFromCategoryRow
	for rows.Next() {
		var i LivestreamSelectManyFromCategoryRow
		if err := rows.Scan(
			&i.CatID,
			&i.CatName,
			&i.CatIsSafe,
			&i.CatViewers,
			&i.CatImage,
			&i.UID,
			&i.UName,
			&i.UIsPartner,
			&i.UAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const livestreamSelectUser = `-- name: LivestreamSelectUser :one
SELECT
    u.avatar AS u_avatar,
    u.is_banned AS u_is_banned,
    u.is_partner AS u_is_partner
FROM
    tc_user u
WHERE
    u.name = $1
`

type LivestreamSelectUserRow struct {
	UAvatar    pgtype.Text
	UIsBanned  pgtype.Bool
	UIsPartner pgtype.Bool
}

func (q *Queries) LivestreamSelectUser(ctx context.Context, name string) (LivestreamSelectUserRow, error) {
	row := q.db.QueryRow(ctx, livestreamSelectUser, name)
	var i LivestreamSelectUserRow
	err := row.Scan(&i.UAvatar, &i.UIsBanned, &i.UIsPartner)
	return i, err
}

const livestreamSelectUserDetails = `-- name: LivestreamSelectUserDetails :one
SELECT
    u.avatar
FROM
    tc_user u
WHERE
    u.name = $1
`

func (q *Queries) LivestreamSelectUserDetails(ctx context.Context, name string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, livestreamSelectUserDetails, name)
	var avatar pgtype.Text
	err := row.Scan(&avatar)
	return avatar, err
}

const livestreamSelectUsersDetails = `-- name: LivestreamSelectUsersDetails :many
SELECT
    u.id,
    u.name,
    u.avatar
FROM
    tc_user u
WHERE
    u.name IN ($1)
`

type LivestreamSelectUsersDetailsRow struct {
	ID     int32
	Name   string
	Avatar pgtype.Text
}

func (q *Queries) LivestreamSelectUsersDetails(ctx context.Context, usernames []string) ([]LivestreamSelectUsersDetailsRow, error) {
	rows, err := q.db.Query(ctx, livestreamSelectUsersDetails, usernames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LivestreamSelectUsersDetailsRow
	for rows.Next() {
		var i LivestreamSelectUsersDetailsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Avatar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const livestreamUpdate = `-- name: LivestreamUpdate :one
WITH updated AS (
    UPDATE tc_livestream
    SET
        title = $1,
        viewers = $2,
        id_category = (SELECT id FROM tc_category c WHERE c.link = $3)
    WHERE
        id_user = (SELECT id FROM tc_user u WHERE u.name = $4)
        RETURNING id, id_user, id_category, started_at, viewers, is_live, is_multistream, title
    )
SELECT
    u.avatar as user_avatar,
    u.name AS user_name,
    c.link AS category_link,
    c.name AS category_name
FROM
    updated
JOIN
    tc_user u ON updated.id_user = u.id
JOIN
    tc_category c ON updated.id_category = c.id
`

type LivestreamUpdateParams struct {
	Title   pgtype.Text
	Viewers pgtype.Int4
	Link    string
	Name    string
}

type LivestreamUpdateRow struct {
	UserAvatar   pgtype.Text
	UserName     string
	CategoryLink string
	CategoryName string
}

func (q *Queries) LivestreamUpdate(ctx context.Context, arg LivestreamUpdateParams) (LivestreamUpdateRow, error) {
	row := q.db.QueryRow(ctx, livestreamUpdate,
		arg.Title,
		arg.Viewers,
		arg.Link,
		arg.Name,
	)
	var i LivestreamUpdateRow
	err := row.Scan(
		&i.UserAvatar,
		&i.UserName,
		&i.CategoryLink,
		&i.CategoryName,
	)
	return i, err
}
