// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.livestream.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const livestreamDelete = `-- name: LivestreamDelete :exec
DELETE FROM
    tc_livestream l
WHERE
    l.id_user = (
        SELECT
            id
        FROM
            tc_user
        WHERE
            name = $1
    )
`

func (q *Queries) LivestreamDelete(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, livestreamDelete, name)
	return err
}

const livestreamInsert = `-- name: LivestreamInsert :one
WITH inserted AS (
    INSERT INTO tc_livestream (
        id_user,
        id_category,
        is_multistream,
        title
    ) VALUES (
        (SELECT id FROM tc_user u WHERE u.name = $1),
        (SELECT id FROM tc_category c WHERE c.link = $2),
        FALSE,
        $3
    )
    RETURNING id, id_user, id_category, viewers, title, is_live, started_at, is_multistream
)
SELECT
    inserted.id AS livestream_id,
    u.avatar AS user_avatar,
    u.name AS user_name,
    c.link AS category_link,
    c.name AS category_name,
    started_at
FROM
    inserted
JOIN
    tc_user u ON inserted.id_user = u.id
JOIN
    tc_category c ON inserted.id_category = c.id
`

type LivestreamInsertParams struct {
	Name  string
	Link  string
	Title pgtype.Text
}

type LivestreamInsertRow struct {
	LivestreamID int32
	UserAvatar   pgtype.Text
	UserName     string
	CategoryLink string
	CategoryName string
	StartedAt    pgtype.Timestamptz
}

func (q *Queries) LivestreamInsert(ctx context.Context, arg LivestreamInsertParams) (LivestreamInsertRow, error) {
	row := q.db.QueryRow(ctx, livestreamInsert, arg.Name, arg.Link, arg.Title)
	var i LivestreamInsertRow
	err := row.Scan(
		&i.LivestreamID,
		&i.UserAvatar,
		&i.UserName,
		&i.CategoryLink,
		&i.CategoryName,
		&i.StartedAt,
	)
	return i, err
}

const livestreamUpdate = `-- name: LivestreamUpdate :one
WITH updated AS (
    UPDATE tc_livestream
    SET
        title = $1,
        viewers = $2,
        id_category = (SELECT id FROM tc_category c WHERE c.link = $3)
    WHERE
        id_user = (SELECT id FROM tc_user u WHERE u.name = $4)
        RETURNING id, id_user, id_category, viewers, title, is_live, started_at, is_multistream
    )
SELECT
    u.avatar as user_avatar,
    u.name AS user_name,
    c.link AS category_link,
    c.name AS category_name
FROM
    updated
JOIN
    tc_user u ON updated.id_user = u.id
JOIN
    tc_category c ON updated.id_category = c.id
`

type LivestreamUpdateParams struct {
	Title   pgtype.Text
	Viewers int32
	Link    string
	Name    string
}

type LivestreamUpdateRow struct {
	UserAvatar   pgtype.Text
	UserName     string
	CategoryLink string
	CategoryName string
}

func (q *Queries) LivestreamUpdate(ctx context.Context, arg LivestreamUpdateParams) (LivestreamUpdateRow, error) {
	row := q.db.QueryRow(ctx, livestreamUpdate,
		arg.Title,
		arg.Viewers,
		arg.Link,
		arg.Name,
	)
	var i LivestreamUpdateRow
	err := row.Scan(
		&i.UserAvatar,
		&i.UserName,
		&i.CategoryLink,
		&i.CategoryName,
	)
	return i, err
}

const livestreamUpdateViewers = `-- name: LivestreamUpdateViewers :exec
UPDATE tc_livestream
    SET
        viewers = $1
    FROM
        tc_user
    WHERE
        tc_livestream.id_user = tc_user.id
    AND
        tc_user.name = $2
`

type LivestreamUpdateViewersParams struct {
	Viewers int32
	Name    string
}

func (q *Queries) LivestreamUpdateViewers(ctx context.Context, arg LivestreamUpdateViewersParams) error {
	_, err := q.db.Exec(ctx, livestreamUpdateViewers, arg.Viewers, arg.Name)
	return err
}
